name: www-courtbouillon deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    env:
      PORT: ${{ secrets.PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      TAKOYAKI: ${{ secrets.TAKOYAKI }}
      USER: ${{ secrets.USER }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Install dependencies
        run: sudo apt-get update -y && sudo apt-get install openssh-client make rsync -y
      - name: Make
        run: make static
      - name: Rsync
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p $PORT $TAKOYAKI >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          rsync -avz --delete -e "ssh -p $PORT" build/ $USER@$TAKOYAKI:/var/www/www-courtbouillon/
